apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
  labels:
    app: nginx
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen       80 default_server;
        server_name  localhost;
        location /prometheus/ {
            proxy_pass  http://prometheus:9090/;
        }
        location /grafana/ {
            proxy_pass  http://grafana:3000/;
        }
        location /deleteStock {
            proxy_pass http://stock:81/deleteStock;
        }
        location /existingStocks {
            proxy_pass http://stock:81/existingStocks;
        }
        location /submitStock {
            proxy_pass http://stock:81/submitStock;
        }
        location /stock/ {
            proxy_pass http://stock:80/;
        }
      }
    }
