apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
      name: nginx
spec:
  replicas: 1
  selector:
      matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - name:  nginx-port
          containerPort:  80
          protocol: TCP
      volumes:
      - name: nginx-conf
        configMap:
          name: nginxconfigmap # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf